/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function Planet(props) {
    const shapeContainer= useRef(null);
    const spereContainer= useRef(null);
    const ringContainer= useRef(null);
  const { nodes, materials } = useGLTF('/models/Planet.glb')

 useGSAP(() => {
  const tl = gsap.timeline({
    defaults: {
      ease: "power3.out",
    },
  });

  // Planet entrance
  tl.from(shapeContainer.current.position, {
    y: 4,
    duration: 2.5,
    ease: "expo.out",
  });

  // Planet body rotation reveal
  tl.from(
    spereContainer.current.rotation,
    {
      x: Math.PI * 0.35,
      y: Math.PI,
      z: 0,
      duration: 4,
      ease: "power2.out",
    },
    "-=1.5"
  );

  // Ring reveal
  tl.from(
    ringContainer.current.rotation,
    {
      x: Math.PI * 0.5,
      y: Math.PI * 0.3,
      z: 0,
      duration: 5,
      ease: "power2.out",
    },
    "-=3"
  );


  // Slow continuous planet rotation
  gsap.to(spereContainer.current.rotation, {
    y: "+=" + Math.PI * 2,
    duration: 60,
    repeat: -1,
    ease: "none",
  });


  // Slow ring rotation
  gsap.to(ringContainer.current.rotation, {
    z: "+=" + Math.PI * 2,
    duration: 80,
    repeat: -1,
    ease: "none",
  });


}, []);


  return (
    <group ref={shapeContainer} {...props} dispose={null}>
        <group ref={spereContainer}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.002']}
        rotation={[0, 0, 0.741]}
      />
       <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere2.geometry}
        material={materials['Material.001']}
        position={[0.647, 1.03, -0.724]}
        rotation={[0, 0, 0.741]}
        scale={0.223}
      />
      </group>
      <mesh
      ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials['Material.001']}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
     
    </group>
  )
}

useGLTF.preload('/models/Planet.glb')
